"""Init

Revision ID: 42513f1b0ebe
Revises: 
Create Date: 2023-02-17 11:56:51.622140

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42513f1b0ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('registration_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
    op.create_table(
        'query_1',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('confidence_score', sa.Integer(), nullable=False),
        sa.Column('tag', sa.String(), nullable=False),
        sa.Column('query_date', sa.DateTime(), nullable=False),
        sa.Column('original_text', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'query_2',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('negative', sa.Integer(), nullable=True),
        sa.Column('neutral', sa.Integer(), nullable=True),
        sa.Column('positive', sa.Integer(), nullable=True),
        sa.Column('angry', sa.Integer(), nullable=True),
        sa.Column('sad', sa.Integer(), nullable=True),
        sa.Column('excited', sa.Integer(), nullable=True),
        sa.Column('bored', sa.Integer(), nullable=True),
        sa.Column('happy', sa.Integer(), nullable=True),
        sa.Column('fear', sa.Integer(), nullable=True),
        sa.Column('query_date', sa.DateTime(), nullable=False),
        sa.Column('original_text', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'query_3',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('abusive', sa.Integer(), nullable=True),
        sa.Column('hate_speech', sa.Integer(), nullable=True),
        sa.Column('neither', sa.Integer(), nullable=True),
        sa.Column('angry', sa.Integer(), nullable=True),
        sa.Column('sad', sa.Integer(), nullable=True),
        sa.Column('excited', sa.Integer(), nullable=True),
        sa.Column('bored', sa.Integer(), nullable=True),
        sa.Column('happy', sa.Integer(), nullable=True),
        sa.Column('fear', sa.Integer(), nullable=True),
        sa.Column('query_date', sa.DateTime(), nullable=False),
        sa.Column('original_text', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_3')
    op.drop_table('query_2')
    op.drop_table('query_1')
    op.drop_table('user')
    # ### end Alembic commands ###
